Import('env')

env.Object(target='Structs', source=['Structs.cpp'])
env.Object(target='FrameGeometry', source=['FrameGeometry.cpp'])
env.Object(target='gzstream', source=['gzstream.cpp'])
env.Object(target='InputParameters', source=['InputParameters.cpp'])
env.Object(target='stdafx', source=['stdafx.cpp'])
env.Object(target='Trajectories', source=['Trajectories.cpp'])
env.Object(target='rmsf', source=['rmsf.cpp'])

rmsf = env.Program(target='rmsf-scons', source=['FrameGeometry', 'gzstream', 'InputParameters','rmsf', 'stdafx', 'Structs', 'Trajectories'])

Return('rmsf')
